---
name: "document_crawl"
fs:
  indexed_chars: 100%
  lang_detect: true
  continue_on_error: true
#  ocr:
#    language: "vie"
#    enabled: true
#    pdf_strategy: "ocr_and_text"
elasticsearch:
  nodes:
    - url: "http://elasticsearch:9200"
#  username: "elastic"
#  password: "changeme"
  ssl_verification: false
rest :
  url: "http://fscrawler:8080"
